#pragma once
#include <Arduino.h>

// Manual, user-initiated firmware updates from GitHub Releases - see
// CLAUDE.md's "OTA + versioning" section and the README's "Firmware
// updates" section.
//
// Flow (deliberately manual - no timer, no auto-download, no auto-install):
//   1. User clicks "Check for updates" on the config page. The POST handler
//      only calls requestCheck(); loop() later runs the actual check: GET
//      the release manifest, compare its version with the compiled-in
//      FW_VERSION.
//   2. If a newer release exists, the page shows an "Install update"
//      button. Its POST handler only calls requestInstall(); loop() later
//      streams the .bin into the inactive OTA slot via Update.h, verifying
//      the manifest's sha256 before the boot pointer is ever moved, then
//      restarts.
//   3. First boot into the new image: the ESP32 bootloader marks it
//      PENDING_VERIFY. This module marks it valid only once the network
//      stack has proven itself (WiFi up + a CelesTrak request that got an
//      HTTP response). If that hasn't happened ~10 min after boot, or the
//      new build crashes/resets before then, the bootloader reverts to the
//      previous slot. See verifyRollbackLater() in ota.cpp.
//
// Both the check and the install are blocking network operations that must
// only ever run from loop(), never from a request handler - same async_tcp
// task-safety rule as everything else (CLAUDE.md "Known gotchas"). The
// request*() calls are just flag sets and are safe from anywhere.
//
// The manifest is a small JSON file published as a GitHub Release asset
// alongside the binary (generated by tools/make_manifest.py in CI):
//   {"version":"1.0.0","url":"https://.../firmware-1.0.0.bin",
//    "sha256":"<64 hex>","size":1134080}
// "url" is always the tag-specific asset URL, never a "latest" alias, so
// a manifest and a binary from two different releases can't get paired up
// if a release is published mid-download.

// GitHub's "latest release" alias - 302-redirects to the newest non-
// prerelease, non-draft release's asset. Overridable per device on the
// config page (NVS), so it can be pointed at a local web server for testing
// before the repo is public, or at a fork's own releases.
static const char* const OTA_DEFAULT_MANIFEST_URL =
    "https://github.com/lueningphilipp/Satellite-Tracker-Buddy/releases/latest/download/manifest.json";

class OtaUpdater {
public:
    // Reads the OTA image state + the "just updated" NVS breadcrumb and
    // sets the initial status text. Call once from setup(), after
    // Serial.begin() - needs no network.
    void begin();

    // Safe from request handlers - only set flags for loop() to act on. The
    // status write here is just a string (no network), safe to do
    // synchronously - it exists so the config page's "Checking for
    // updates..." page (which polls status() over /config) always sees an
    // in-progress result starting the instant the button is clicked,
    // rather than possibly polling once before loop() has even picked up
    // checkRequested and briefly reading a stale leftover status from
    // before this click as if it were already the new answer.
    void requestCheck() {
        checkRequested = true;
        setStatus(false, "checking - queued...");
    }
    // Returns false (and schedules nothing) if no update is currently
    // known - the page only shows the install button after a successful
    // check, but a scripted POST could still hit the route.
    bool requestInstall();

    // Call from loop() only. Runs a pending check/install, and handles the
    // post-update health mark / rollback timeout. networkHealthy: WiFi is
    // up AND the TLS/HTTP stack has produced a real response (see
    // main.cpp for the exact criterion).
    void loop(const String& manifestUrl, bool wifiConnected, bool networkHealthy);

    // True when the compiled version is a plain x.y.z, i.e. a tagged release
    // build. Dev builds ("0.9.4-3-gabc1234", "abc1234-dirty", "unknown")
    // never compare or update - there's no meaningful ordering for them.
    bool enabled() const { return releaseBuild; }
    bool updateAvailable() const { return haveUpdate; }
    String availableVersion() const { return haveUpdate ? String(availVersion) : String(); }
    String status() const { return String(statusBuf); }
    // True when the current status text describes a failure (for the
    // config page's red highlight).
    bool statusIsError() const { return statusError; }

private:
    void check(const String& manifestUrl, bool wifiConnected);
    void install(bool wifiConnected);
    void handleRollback(bool networkHealthy);
    void setStatus(bool isError, const char* fmt, ...);
    void writeBreadcrumb(const char* from, const char* to);
    void clearBreadcrumb();

    volatile bool checkRequested = false;
    volatile bool installRequested = false;
    bool releaseBuild = false;
    bool pendingVerify = false;   // running image is PENDING_VERIFY (first boot after an OTA)
    bool haveUpdate = false;
    bool statusError = false;

    // Fixed buffers rather than Strings: these are written from loop()
    // (including many times during a download) while the config page's
    // GET handler may read them concurrently from the async_tcp task. A
    // torn read of a char buffer is at worst garbled text for one page
    // load; a String reallocating underneath another core's read is a
    // crash.
    char statusBuf[160] = "not checked yet";
    char availVersion[24] = "";
    char availUrl[256] = "";
    char availSha256[65] = "";
    size_t availSize = 0;
};

extern OtaUpdater ota;
