#!/usr/bin/env python3
"""
Exports the demo's embedded 360x180 land mask as a PROGMEM-packed 1bpp C
array for firmware, so the two never drift apart (reads MASK_B64 straight out
of sat_display_demo.py rather than a hand-copied duplicate).

Threshold matches demo's land_grid() exactly: land_img.get_at((x,y))[0] > 100
(land_img is native 360x180 already, so no resampling needed for the e-paper
renderer, which uses the mask at that exact resolution).

    python tools/mask_to_progmem.py
    -> writes firmware/src/display/land_mask.h
"""
import re, sys, io, base64, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEMO = ROOT / "demo" / "sat_display_demo.py"
OUT = ROOT / "firmware" / "src" / "display" / "land_mask.h"

W, H = 360, 180

def main():
    src = DEMO.read_text()
    m = re.search(r'MASK_B64\s*=\s*"([^"]+)"', src)
    if not m:
        sys.exit("Couldn't find MASK_B64 in " + str(DEMO))
    png_bytes = base64.b64decode(m.group(1))

    import pygame
    pygame.init()
    img = pygame.image.load(io.BytesIO(png_bytes)).convert(24)
    if img.get_size() != (W, H):
        sys.exit(f"Expected a {W}x{H} mask, got {img.get_size()} - "
                  f"check W/H in this script match the demo's land_grid(360, 180) call")

    # Pack row-major, 1 bit/pixel, MSB first, each row padded to a whole byte
    # (matches the common PROGMEM-bitmap convention, e.g. Adafruit_GFX's
    # drawBitmap): row width in bytes = ceil(W/8).
    row_bytes = (W + 7) // 8
    data = bytearray(row_bytes * H)
    for y in range(H):
        for x in range(W):
            land = img.get_at((x, y))[0] > 100
            if land:
                data[y * row_bytes + x // 8] |= 0x80 >> (x % 8)

    lines = []
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"// Auto-generated by tools/mask_to_progmem.py from demo/sat_display_demo.py's")
    lines.append(f"// MASK_B64 - do not hand-edit, regenerate instead if the demo's mask changes.")
    lines.append(f"static const int LAND_MASK_W = {W};")
    lines.append(f"static const int LAND_MASK_H = {H};")
    lines.append(f"static const int LAND_MASK_ROW_BYTES = {row_bytes};")
    lines.append(f"static const uint8_t LAND_MASK[{len(data)}] PROGMEM = {{")
    for i in range(0, len(data), 20):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i+20])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append("// True if (x, y) - 0<=x<360, 0<=y<180 - is land.")
    lines.append("inline bool landAt(int x, int y) {")
    lines.append("    uint8_t byte = pgm_read_byte(&LAND_MASK[y * LAND_MASK_ROW_BYTES + x / 8]);")
    lines.append("    return (byte >> (7 - (x % 8))) & 1;")
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(data)} bytes packed, {W}x{H} 1bpp)")

if __name__ == "__main__":
    main()
